// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBicds8Fdspr6n377IdIRLjRAsOXzL124',
    appId: '1:701859352905:web:a7c28811f63f18d47d0a98',
    messagingSenderId: '701859352905',
    projectId: 'smart-port-8ba03',
    authDomain: 'smart-port-8ba03.firebaseapp.com',
    storageBucket: 'smart-port-8ba03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEONen9O2LuSvaZtOgV5xSpvAWcFQN0DU',
    appId: '1:701859352905:android:fa9e9abc1005c4887d0a98',
    messagingSenderId: '701859352905',
    projectId: 'smart-port-8ba03',
    storageBucket: 'smart-port-8ba03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBePQsml9VGrD52pBvlyXn0o2_SjyzGk',
    appId: '1:701859352905:ios:1059ebaecf4a0f107d0a98',
    messagingSenderId: '701859352905',
    projectId: 'smart-port-8ba03',
    storageBucket: 'smart-port-8ba03.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectCustomerWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBePQsml9VGrD52pBvlyXn0o2_SjyzGk',
    appId: '1:701859352905:ios:1059ebaecf4a0f107d0a98',
    messagingSenderId: '701859352905',
    projectId: 'smart-port-8ba03',
    storageBucket: 'smart-port-8ba03.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectCustomerWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBicds8Fdspr6n377IdIRLjRAsOXzL124',
    appId: '1:701859352905:web:4297c64e797b8cd87d0a98',
    messagingSenderId: '701859352905',
    projectId: 'smart-port-8ba03',
    authDomain: 'smart-port-8ba03.firebaseapp.com',
    storageBucket: 'smart-port-8ba03.firebasestorage.app',
  );
}
